version: '3'
services:
  db:
    image: mysql:8
    container_name: mymysql
    restart: always
    environment:
      MYSQL_DATABASE: golf_club_db
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3306:3306"
  app:
    build: .
    container_name: golf-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/golf_club_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password123
